"use client";
import {useMemo,useState} from "react";
const clientes=[
{id:1,nome:"Supermercado Central",cidade:"Ciudad del Este",canal:"Supermercado",dias:18,produtos:[{nome:"Personalidade G",estoque:3,venda:12,compras:[["05/09",3,12],["17/08",2,12],["12/08",3,12]]},{nome:"Personalidade M",estoque:0,venda:10,compras:[["07/09",0,10],["24/08",2,10],["10/08",4,10]]},{nome:"Higifral",estoque:8,venda:12,compras:[["06/09",8,12],["23/08",7,12],["09/08",9,12]]}]},
{id:2,nome:"Comercial Paraná",cidade:"Presidente Franco",canal:"Mayorista",dias:26,produtos:[{nome:"Personalidade G",estoque:1,venda:18,compras:[["02/09",1,18],["12/08",4,16],["22/07",2,16]]},{nome:"Personalidade XG",estoque:0,venda:12,compras:[["02/09",0,12],["12/08",1,12],["22/07",3,10]]}]},
{id:3,nome:"Mercado San José",cidade:"Minga Guazú",canal:"Supermercado",dias:11,produtos:[{nome:"Personalidade M",estoque:7,venda:8,compras:[["11/09",7,8],["28/08",5,8],["14/08",6,8]]},{nome:"Higifral",estoque:5,venda:6,compras:[["11/09",5,6],["28/08",4,6],["14/08",5,6]]}]}];
function calc(p){const media=p.compras.reduce((s,x)=>s+x[2],0)/p.compras.length;const cobertura=p.estoque/(media||1);const sug=Math.max(0,Math.ceil(media*1.15-p.estoque));const status=p.estoque===0?"Ruptura":cobertura<.35?"Atenção":"Normal";return{media:Math.round(media),sug,status};}
export default function Home(){const [aba,setAba]=useState("Visão geral");const [cliente,setCliente]=useState(clientes[0]);const [busca,setBusca]=useState("");const [visita,setVisita]=useState(false);const lista=useMemo(()=>clientes.filter(c=>c.nome.toLowerCase().includes(busca.toLowerCase())||c.cidade.toLowerCase().includes(busca.toLowerCase())),[busca]);const rupturas=cliente.produtos.filter(p=>calc(p).status==="Ruptura").length;return <main><header><div><small>AUSTEN · GRUPO EUROFRAL</small><h1>Austen Comercial</h1><p>Execução de campo, estoque e reposição inteligente.</p></div><button onClick={()=>setVisita(!visita)}>{visita?"Finalizar visita":"+ Nova visita"}</button></header>
<section className="kpis"><article><span>Clientes da rota</span><b>24</b><small>18 visitados</small></article><article><span>Meta do mês</span><b>78%</b><small>alvo de crescimento +12%</small></article><article><span>Rupturas no cliente</span><b>{rupturas}</b><small>ação imediata</small></article><article><span>Última visita</span><b>{cliente.dias}d</b><small>{cliente.nome}</small></article></section>
<div className="workspace"><aside><h3>Minha rota</h3><input placeholder="Buscar cliente..." value={busca} onChange={e=>setBusca(e.target.value)}/>{lista.map(c=><button className={"client "+(c.id===cliente.id?"active":"")} key={c.id} onClick={()=>setCliente(c)}><strong>{c.nome}</strong><span>{c.cidade} · {c.canal}</span></button>)}</aside>
<section className="panel"><div className="title"><div><small>{visita?"VISITA EM ANDAMENTO":"CLIENTE SELECIONADO"}</small><h2>{cliente.nome}</h2><p>{cliente.cidade} · {cliente.canal} · última visita há {cliente.dias} dias</p></div><span className={"pill "+(visita?"live":"")}>{visita?"Visita aberta":"Pronto para visitar"}</span></div>
<div className="products">{cliente.produtos.map(p=>{const x=calc(p);return <article className="product" key={p.nome}><div className="productHead"><div><h3>{p.nome}</h3><span className={"status "+x.status.toLowerCase()}>{x.status}</span></div><div className="numbers"><div><small>Estoque atual</small><b>{p.estoque}</b></div><div><small>Média vendas</small><b>{x.media}</b></div><div className="suggest"><small>Pedido sugerido</small><b>{x.sug}</b></div></div></div><div className="history"><strong>3 compras mais recentes</strong>{p.compras.map((h,i)=><span key={i}><b>{h[0]}</b> · estoque {h[1]} · venda {h[2]}</span>)}</div>{x.status==="Ruptura"&&<div className="alert">Ruptura detectada — priorizar reposição neste atendimento.</div>}</article>})}</div></section></div>
<nav>{["Visão geral","Clientes","Visitas","Pedidos","Metas"].map(n=><button key={n} className={aba===n?"sel":""} onClick={()=>setAba(n)}>{n}</button>)}</nav></main>}